-- Seed Data for Financial Application
--
-- This file creates test data for development and testing:
-- - 5 test accounts (Alice, Bob, Charlie, Diana, Eve)
-- - Security records with mock credentials for each account
-- - Sample transactions between accounts
--
-- Password for all accounts: "password123" (hashed with bcrypt)
-- Hash: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi

-- ============================================================
-- Insert Test Accounts
-- ============================================================

INSERT INTO Accounts (account_name) VALUES
    ('Alice Account'),
    ('Bob Account'),
    ('Charlie Account'),
    ('Diana Account'),
    ('Eve Account');

-- ============================================================
-- Insert Account Security Records
-- ============================================================
-- Note: In production, password hashes would be generated by the application
-- using a proper bcrypt library with appropriate salt rounds

INSERT INTO AccountSecurity (account_id, username, password_hash)
SELECT 
    account_id,
    CASE 
        WHEN account_name = 'Alice Account' THEN 'user_a'
        WHEN account_name = 'Bob Account' THEN 'user_b'
        WHEN account_name = 'Charlie Account' THEN 'user_c'
        WHEN account_name = 'Diana Account' THEN 'user_d'
        WHEN account_name = 'Eve Account' THEN 'user_e'
    END as username,
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi' as password_hash
FROM Accounts;

-- ============================================================
-- Insert Sample Transactions
-- ============================================================
-- Creates a variety of transactions between different accounts
-- with different amounts and dates over the past 30 days

-- Get account IDs for reference
DO $$
DECLARE
    alice_id UUID;
    bob_id UUID;
    charlie_id UUID;
    diana_id UUID;
    eve_id UUID;
BEGIN
    SELECT account_id INTO alice_id FROM Accounts WHERE account_name = 'Alice Account';
    SELECT account_id INTO bob_id FROM Accounts WHERE account_name = 'Bob Account';
    SELECT account_id INTO charlie_id FROM Accounts WHERE account_name = 'Charlie Account';
    SELECT account_id INTO diana_id FROM Accounts WHERE account_name = 'Diana Account';
    SELECT account_id INTO eve_id FROM Accounts WHERE account_name = 'Eve Account';
    
    -- Initial deposits (from external source - Eve acts as bank)
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (eve_id, alice_id, 1000.00, CURRENT_DATE - INTERVAL '30 days'),
    (eve_id, bob_id, 1500.00, CURRENT_DATE - INTERVAL '30 days'),
    (eve_id, charlie_id, 2000.00, CURRENT_DATE - INTERVAL '30 days'),
    (eve_id, diana_id, 1200.00, CURRENT_DATE - INTERVAL '30 days');
    
    -- Week 1 transactions
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, bob_id, 50.00, CURRENT_DATE - INTERVAL '28 days'),
    (bob_id, charlie_id, 75.50, CURRENT_DATE - INTERVAL '27 days'),
    (charlie_id, diana_id, 100.00, CURRENT_DATE - INTERVAL '26 days'),
    (diana_id, alice_id, 25.75, CURRENT_DATE - INTERVAL '25 days');
    
    -- Week 2 transactions
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, charlie_id, 150.00, CURRENT_DATE - INTERVAL '21 days'),
    (bob_id, diana_id, 200.00, CURRENT_DATE - INTERVAL '20 days'),
    (charlie_id, alice_id, 80.25, CURRENT_DATE - INTERVAL '19 days'),
    (diana_id, bob_id, 45.50, CURRENT_DATE - INTERVAL '18 days');
    
    -- Week 3 transactions
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, diana_id, 120.00, CURRENT_DATE - INTERVAL '14 days'),
    (bob_id, alice_id, 90.00, CURRENT_DATE - INTERVAL '13 days'),
    (charlie_id, bob_id, 110.75, CURRENT_DATE - INTERVAL '12 days'),
    (diana_id, charlie_id, 65.00, CURRENT_DATE - INTERVAL '11 days');
    
    -- Week 4 transactions
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, bob_id, 75.00, CURRENT_DATE - INTERVAL '7 days'),
    (bob_id, charlie_id, 95.50, CURRENT_DATE - INTERVAL '6 days'),
    (charlie_id, diana_id, 130.00, CURRENT_DATE - INTERVAL '5 days'),
    (diana_id, alice_id, 55.25, CURRENT_DATE - INTERVAL '4 days');
    
    -- Recent transactions
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, charlie_id, 40.00, CURRENT_DATE - INTERVAL '3 days'),
    (bob_id, diana_id, 85.00, CURRENT_DATE - INTERVAL '2 days'),
    (charlie_id, alice_id, 60.50, CURRENT_DATE - INTERVAL '1 day'),
    (diana_id, bob_id, 70.00, CURRENT_DATE);
    
    -- Additional transactions for variety (total: 28 transactions)
    INSERT INTO Transactions (source_account_id, target_account_id, amount, transaction_date) VALUES
    (alice_id, diana_id, 35.00, CURRENT_DATE - INTERVAL '15 days'),
    (bob_id, alice_id, 125.00, CURRENT_DATE - INTERVAL '10 days'),
    (charlie_id, bob_id, 88.50, CURRENT_DATE - INTERVAL '8 days'),
    (diana_id, charlie_id, 92.75, CURRENT_DATE - INTERVAL '9 days');
    
END $$;
