-- Seed Data for Financial Application (SQL Server)
--
-- This file creates test data for development and testing:
-- - 5 test accounts (Alice, Bob, Charlie, Diana, Eve)
-- - Security records with mock credentials for each account
-- - Sample transactions between accounts
--
-- Password for all accounts: "password123" (hashed with bcrypt)
-- Hash: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi

-- ============================================================
-- Insert Test Accounts
-- ============================================================

INSERT INTO Accounts (Id, AccountName, CreatedAt, UpdatedAt) VALUES
    ('550e8400-e29b-41d4-a716-446655440001', 'Alice Account', GETUTCDATE(), GETUTCDATE()),
    ('550e8400-e29b-41d4-a716-446655440002', 'Bob Account', GETUTCDATE(), GETUTCDATE()),
    ('550e8400-e29b-41d4-a716-446655440003', 'Charlie Account', GETUTCDATE(), GETUTCDATE()),
    ('550e8400-e29b-41d4-a716-446655440004', 'Diana Account', GETUTCDATE(), GETUTCDATE()),
    ('550e8400-e29b-41d4-a716-446655440005', 'Eve Account', GETUTCDATE(), GETUTCDATE());

-- ============================================================
-- Insert Account Security Records
-- ============================================================
-- Note: In production, password hashes would be generated by the application
-- using a proper bcrypt library with appropriate salt rounds

INSERT INTO AccountSecurity (Id, AccountId, Username, PasswordHash, CreatedAt) VALUES
    ('650e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', 'user_a', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi', GETUTCDATE()),
    ('650e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440002', 'user_b', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi', GETUTCDATE()),
    ('650e8400-e29b-41d4-a716-446655440003', '550e8400-e29b-41d4-a716-446655440003', 'user_c', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi', GETUTCDATE()),
    ('650e8400-e29b-41d4-a716-446655440004', '550e8400-e29b-41d4-a716-446655440004', 'user_d', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi', GETUTCDATE()),
    ('650e8400-e29b-41d4-a716-446655440005', '550e8400-e29b-41d4-a716-446655440005', 'user_e', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqYj5rG5mi', GETUTCDATE());

-- ============================================================
-- Insert Sample Transactions
-- ============================================================
-- Creates a variety of transactions between different accounts
-- with different amounts and dates over the past 30 days

DECLARE @alice_id NVARCHAR(255) = '550e8400-e29b-41d4-a716-446655440001';
DECLARE @bob_id NVARCHAR(255) = '550e8400-e29b-41d4-a716-446655440002';
DECLARE @charlie_id NVARCHAR(255) = '550e8400-e29b-41d4-a716-446655440003';
DECLARE @diana_id NVARCHAR(255) = '550e8400-e29b-41d4-a716-446655440004';
DECLARE @eve_id NVARCHAR(255) = '550e8400-e29b-41d4-a716-446655440005';

-- Initial deposits (from external source - Eve acts as bank)
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440001', @eve_id, @alice_id, 1000.00, DATEADD(day, -30, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440002', @eve_id, @bob_id, 1500.00, DATEADD(day, -30, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440003', @eve_id, @charlie_id, 2000.00, DATEADD(day, -30, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440004', @eve_id, @diana_id, 1200.00, DATEADD(day, -30, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());

-- Week 1 transactions
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440005', @alice_id, @bob_id, 50.00, DATEADD(day, -28, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440006', @bob_id, @charlie_id, 75.50, DATEADD(day, -27, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440007', @charlie_id, @diana_id, 100.00, DATEADD(day, -26, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440008', @diana_id, @alice_id, 25.75, DATEADD(day, -25, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());

-- Week 2 transactions
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440009', @alice_id, @charlie_id, 150.00, DATEADD(day, -21, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440010', @bob_id, @diana_id, 200.00, DATEADD(day, -20, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440011', @charlie_id, @alice_id, 80.25, DATEADD(day, -19, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440012', @diana_id, @bob_id, 45.50, DATEADD(day, -18, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());

-- Week 3 transactions
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440013', @alice_id, @diana_id, 120.00, DATEADD(day, -14, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440014', @bob_id, @alice_id, 90.00, DATEADD(day, -13, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440015', @charlie_id, @bob_id, 110.75, DATEADD(day, -12, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440016', @diana_id, @charlie_id, 65.00, DATEADD(day, -11, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());

-- Week 4 transactions
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440017', @alice_id, @bob_id, 75.00, DATEADD(day, -7, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440018', @bob_id, @charlie_id, 95.50, DATEADD(day, -6, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440019', @charlie_id, @diana_id, 130.00, DATEADD(day, -5, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440020', @diana_id, @alice_id, 55.25, DATEADD(day, -4, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());

-- Recent transactions
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440021', @alice_id, @charlie_id, 40.00, DATEADD(day, -3, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440022', @bob_id, @diana_id, 85.00, DATEADD(day, -2, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440023', @charlie_id, @alice_id, 60.50, DATEADD(day, -1, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440024', @diana_id, @bob_id, 70.00, CAST(GETUTCDATE() AS DATE), GETUTCDATE());

-- Additional transactions for variety (total: 28 transactions)
INSERT INTO Transactions (Id, SourceAccountId, TargetAccountId, Amount, TransactionDate, CreatedAt) VALUES
('750e8400-e29b-41d4-a716-446655440025', @alice_id, @diana_id, 35.00, DATEADD(day, -15, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440026', @bob_id, @alice_id, 125.00, DATEADD(day, -10, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440027', @charlie_id, @bob_id, 88.50, DATEADD(day, -8, CAST(GETUTCDATE() AS DATE)), GETUTCDATE()),
('750e8400-e29b-41d4-a716-446655440028', @diana_id, @charlie_id, 92.75, DATEADD(day, -9, CAST(GETUTCDATE() AS DATE)), GETUTCDATE());
